[package]
name = "run_sim_json"
version = "0.1.0"
edition = "2021"

[dependencies]

reflect = { path = "../reflect" }
reflect_glium = { path = "../reflect_glium" }
reflect_mirrors = { path = "../reflect_mirrors" }
reflect_json = { path = "../reflect_json" }