[package]
name = "miroir_shapes"
version = "0.1.0"
edition = "2021"

[dependencies]

miroir = { path = "../miroir_core", default-features = false }
arrayvec = { version = "0.7", default-features = false }