[package]
name = "gen_rand_sim"
version = "0.1.0"
edition = "2021"

[dependencies]

reflect = { path = "../reflect" }
reflect_mirrors = { path = "../reflect_mirrors" }
reflect_json = { path = "../reflect_json" }
reflect_random = { path = "../reflect_random" }