[package]
name = "reflect_mirrors"
version = "0.1.0"
edition = "2021"

[dependencies]

reflect = { path = "../reflect" }
reflect_glium = { path = "../reflect_glium" }
reflect_json = { path = "../reflect_json" }
