[package]
name = "reflect"
version = "0.1.0"
edition = "2021"

[dependencies]

nalgebra = { version = "0.33", default-features = false }
impl-trait-for-tuples = "0.2"

[features]

default = ["alloc", "std"]
alloc = ["nalgebra/alloc"]
libm = ["nalgebra/libm"]
std = ["nalgebra/std"]